name: "Dotnet version bumper"
description: "Automatically bump project and product versions based on commit messages."

env:
  GH_TOKEN: ${{ secrets.BYPASS_PROTECTED_BRANCHES_PAT }}

runs:
  using: "composite"
  if: "${{ (startsWith(github.event.head_commit.message, 'feat')) || (startsWith(github.event.head_commit.message, 'fix')) || (startsWith(github.event.head_commit.message, 'release'))}}"
  runs-on: ubuntu-latest
  permissions:
    # Give the default GITHUB_TOKEN write permission to commit and push the
    # added or changed files to the repository.
    contents: write
  defaults:
    run:
      working-directory: ./dotnet_geolabsuite

  steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.BYPASS_PROTECTED_BRANCHES_PAT }}
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Set AUTH values from token
      run: echo "PAT_USER=$(gh api user | jq -r '.login')" >> "$GITHUB_ENV"

    - name: Set GIT identity
      run: |
        git config --global user.name '${{ env.PAT_USER }}'
        git config --global user.email '${{ env.PAT_USER }}@users.noreply.github.com'

    - name: Bump project versions
      run: python version_bumper.py
      if: "${{ (!startsWith(github.event.head_commit.message, 'release')) }}"
    
    - name: Bump product versions
      run: python version_bumper.py --release
      if: "${{ (startsWith(github.event.head_commit.message, 'release')) }}"

    - name: Push changes
      run: |
        git push --force
        git push --tags