name: "DotNetVersionize Generate GH release"
description: "Generate GitHub release when a bump release tag is pushed using DotNetVersionize - bump_product_version."

inputs: 
  BYPASS_PROTECTED_BRANCHES_PAT:
    description: "GitHub Token with permissions to push changes on protected branches."
    required: true

runs:
  using: "composite"
  if: "${{ (startsWith(github.event.head_commit.message, 'bump(release)')) }}"
  runs-on: ubuntu-latest
  permissions:
    contents: write
  defaults:
    run:
      working-directory: .

  steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.BYPASS_PROTECTED_BRANCHES_PAT }}
    - name: Set release variables
      run: |
        echo "RELEASE_TAG=$(git tag --sort=committerdate | grep -o 'v.*' | tail -1)" >> "$GITHUB_ENV"
        echo "OLD_RELEASE_TAG=$(git tag --sort=committerdate | grep -o 'v.*' | tail -2 | head -1)" >> "$GITHUB_ENV"
        echo "RELEASE_TITLE=$(git log -1 --pretty=format:%s | cut -d ':' -f 2 | awk '{$1=$1;print}')" >> "$GITHUB_ENV"
    - name: Generate release
      run: |
        gh release create '${{ env.RELEASE_TAG }}' \
          --verify-tag \
          --latest \
          --title '${{ env.RELEASE_TITLE }}' \
          --generate-notes \
          --notes-start-tag '${{ env.OLD_RELEASE_TAG }}'