name: "DotNetVersionize version bumper"
description: "Automatically bump project and product versions based on commit messages."

inputs: 
  BYPASS_PROTECTED_BRANCHES_PAT:
    description: "GitHub Token with permissions to push changes on protected branches."
    required: true

runs:
  using: "composite"
  if: "${{ (startsWith(github.event.head_commit.message, 'feat')) || (startsWith(github.event.head_commit.message, 'fix')) || (startsWith(github.event.head_commit.message, 'release'))}}"
  runs-on: ubuntu-latest
  permissions:
    # Give the default GITHUB_TOKEN write permission to commit and push the
    # added or changed files to the repository.
    contents: write
  defaults:
    run:
      working-directory: .

  steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ inputs.BYPASS_PROTECTED_BRANCHES_PAT }}
        
    - name: Set AUTH values from token
      run: echo "PAT_USER=$(gh api user | jq -r '.login')" >> "$GITHUB_ENV"

    - name: Set GIT identity
      run: |
        git config --global user.name '${{ env.PAT_USER }}'
        git config --global user.email '${{ env.PAT_USER }}@users.noreply.github.com'

    - uses: prefix-dev/setup-pixi@v0.9.0
      with:
        pixi-version: v0.49.0

    - name: Bump project versions
      run: pixi run dotnetversionize
      if: "${{ (!startsWith(github.event.head_commit.message, 'release')) }}"
    
    - name: Bump product versions
      run: pixi run dotnetversionize --release
      if: "${{ (startsWith(github.event.head_commit.message, 'release')) }}"

    - name: Push changes
      run: |
        git push --force
        git push --tags